# Default application configuration that all configurations inherit from.
exclude: [
]

linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: false

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: false # Allow `@include breakpoint` after child classes.

  DuplicateProperty:
    enabled: true

  EmptyLineBetweenBlocks:
    enabled: true

  EmptyRule:
    enabled: true

  HexFormat:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 4

  LeadingZero:
    enabled: false

  NameFormat:
    enabled: false

  PlaceholderInExtend:
    enabled: true

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: true
    extra_properties: [
      break-inside
    ]

  SelectorDepth:
    enabled: true
    max_depth: 3

  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM

  Shorthand:
    enabled: false

  SingleLinePerSelector:
    enabled: true

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  StringQuotes:
    enabled: true
    style: single_quotes # or double_quotes

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UrlQuotes:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false

  IdSelector:
    enabled: false
